name: 3D Profile
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: kushal-1007
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: "generate 3d contribution graph"
          file_pattern: profile-3d-contrib/*.svg
